version: "3"

services:

  runtime-setup:
    image: swift-metrics:20.04-5.7
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.7-focal"

  test:
    image: swift-metrics:20.04-5.7
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-metrics:20.04-5.7
